### ISSUE TITLE
[Bug] Inline validation fails silently, no errors reported

### ISSUE THREAD

**Issue by agoldis** [paypal/paypal-js#100]
### 🐞 Describe the Bug

Inline CC validation fails silently.

`onError` is not called when inline credit card form validation fails. The console has an error message, but it's not communicated, leaving our clients clueless about 

### 🔬 Minimal Reproduction

https://paypal-staging.invoicesimple.com/checkout/BwUXs9i6dU

Use the following CC details: 
4242...
405 Lexington Ave, New York, NY  United States
ZIP code: **101174** << Enter this invalid ZIP code

### 😕 Actual Behavior

Nothing's happening. There's a console error from some paypal internal library:

`ppxo_inline_guest_unhandled_error`

```json
{
  "handledErrors": [
    {
      "billingAddress": {
        "contentKey": "fieldErrors.postalCodeInvalid",
        "field": "postalCode"
      }
    }
  ],
  "unhandledErrors": [],
  "inline_guest_version": "2.12.8",
  "timestamp": 1626133611140,
  "windowID": "d4ef436b46",
  "pageID": "19427c4852",
  "referer": "www.sandbox.paypal.com",
  "host": "www.sandbox.paypal.com",
  "path": "/smart/card-fields",
  "env": "sandbox",
  "country": "CA",
  "lang": "en",
  "uid": "uid_e90d1db9c5_mjm6mjg6ndc",
  "ver": "2.12.8"
}
```

### 🤔 Expected Behavior

There should be an informative error message displayed and `onError` should be called

### 🌍 Environment

-   Node.js/npm: n/A
-   OS: n/A
-   Browser: Chrome / Firefox

### ➕ Additional Context

Might be related https://github.com/paypal/paypal-checkout-components/issues/1550

We have been partnering via PayPal Commerce Platform for high-volume invoice payments processing, and  this one causes a real issue for real customers in production systems. 

It's kind of crazy that the issue is taking so long to resolve, considering the impact.

**Comment by gregjopa** [comment]
This issue is not directly related to paypal-js. Let's use https://github.com/paypal/paypal-checkout-components/issues/1550 to track it since checkout-components is the main repo for reporting issues with the PayPal JS SDK.

**Comment by sthondepu** [comment]
Hi @agoldis - Is this resolved? I'm facing this type of issue and above links getting 404 error.
