### ISSUE TITLE
[Bug] order.authorize() return type is missing payments

### ISSUE THREAD

**Issue by florianmutter** [paypal/paypal-js#107]
### 🐞 Describe the Bug

According to https://developer.paypal.com/docs/api/orders/v2/#orders_authorize the authorization id can be found in the returned data but the `PurchaseUnit` type is missing the payments object.

### 😕 Actual Behavior

typescript reports an error when trying to access payments:
```
error TS2339: Property 'payments' does not exist on type 'PurchaseUnit'.

40     details.purchase_units[0].payments.authorizations[0].id,
                                 ~~~~~~~~
```

### 🤔 Expected Behavior

compilation works

### 🌍 Environment

-   Node.js/npm: -
-   OS: -
-   Browser: -

**Comment by gregjopa** [comment]
Hi @florianmutter thanks for reporting this issue with missing types for authorize(). This error should be fixed in the latest release which is 4.0.7.

I'm going to close this out. Feel free to reopen if you are still getting type errors with authorize().
