### ISSUE TITLE
[Bug] Type OnApproveActions incorrectly defines restart() to be part of order

### ISSUE THREAD

**Issue by tdahlhoff** [paypal/paypal-js#112]
When using Types PayPalNamespace paypal.Buttons onApprove Callbacks Parameter actions is of Type OnApproveActions. I should be able to call actions.restart() but OnApproveActions type is defined to use actions.order.restart() which leads to Error "actions.order.restart is not a function".

```
export type OnApproveActions = {
    order: {
        capture: () => Promise<OrderResponseBody>;
        authorize: () => Promise<OrderResponseBody>;
        redirect: (redirectURL: string) => void;
        restart: () => void;
    };
};
```

Should at least be 

```
export type OnApproveActions = {
    order: {
        capture: () => Promise<OrderResponseBody>;
        authorize: () => Promise<OrderResponseBody>;
        redirect: (redirectURL: string) => void;
    };
    restart: () => void;
};
```

Perhaps all methods should not be listed under order, I did not check this yet.

**Comment by gregjopa** [comment]
Thanks for reporting this bug @tdahlhoff! It's been fixed and is included in the latest release which is 4.0.8
