### ISSUE TITLE
[Feature] Support multiple shipping options

### ISSUE THREAD

**Issue by florianmutter** [paypal/paypal-js#127]
### 🚀 Feature Proposal

Support multiple shipping options as described here: https://developer.paypal.com/docs/business/checkout/configure-payments/shipping-options/

### Motivation

Allowing the user to choose between multiple shipping options improve the ux for express checkout.

Extra note: I could not find how this is done in the Order API documentation here: https://developer.paypal.com/docs/api/orders/v2/

**Comment by gregjopa** [comment]
Hi @florianmutter I think this is related to #134. I think this should be resolved once we get proper types for `onShippingChange`.

**Comment by gregjopa** [comment]
Fixed by #135
