### ISSUE TITLE
[Bug] Bug report onShippingChange is not up to date with PayPal Javascript SDK

### ISSUE THREAD

**Issue by LiamSnow** [paypal/paypal-js#134]
### 🐞 Describe the Bug

As per [this article](https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/) the onShippingChange() method should take in two parameters (data and actions) and return actions. In this library, however, it takes in no parameters and returns void ([source](https://github.com/paypal/paypal-js/blob/51bb788722f566647973b7d7abe7a8f82d4e225b/types/components/buttons.d.ts#L108));

### ➕ Additional Context

This is a very minor issue and I have managed to get around it with a ts-ignore, but I figured I would let you guys know about it. I can submit a pull request to modify [buttons.d.ts](https://github.com/paypal/paypal-js/blob/51bb788722f566647973b7d7abe7a8f82d4e225b/types/components/buttons.d.ts#L108) but I want to make sure this is the only file that requires changes.

**Comment by gregjopa** [comment]
Hi @LiamSnow, good catch with this bug! The `onShippingChange()` function is missing proper TypeScript types.  

I would happily accept a pull request for this. Here are the flow types from the actual source code: https://github.com/paypal/paypal-smart-payment-buttons/blob/2c3407d19789d7c01ac320b8ba4249e8fddd9a5b/src/props/onShippingChange.js#L13-L43. These just need to be converted to TypeScript and added to the `buttons.d.ts` file.

**Comment by LiamSnow** [comment]
Hi @gregjopa, thanks for the fast response!

I submitted a pull request [here](https://github.com/paypal/paypal-js/pull/135). Please tell me if there any are any issues with it.

**Comment by gregjopa** [comment]
Fixed by #135
