### ISSUE TITLE
Venmo button does not appear.

### ISSUE THREAD

**Issue by gadicker** [paypal/paypal-js#163]
I am trying to add the Venmo button by setting 'enable-funding': 'venmo' but the Venmo button does not appear.  I can get others like eps and ideal but venmo does not.  I am using USD for currency.  Is there something else I am missing to allow the venmo button?

As a side note, right now I only need the Venmo button but if I wanted to have both Venmo and Ideal is there a way I could do that with this package? 

Here is the loadScript I am trying to use:
        loadScript({
          'client-id': paypalClientId,
          'disable-funding': 'credit',
          'enable-funding': 'venmo',
          'vault': false,
          'merchant-id': this.clientInfo.paypal_email,
          'currency': this.invoice.currSymbol,
        })

and the currSymbol is USD in this case.

**Comment by gregjopa** [comment]
Hi @gadicker, I think there are certain eligibility restrictions with Venmo (ex: must be US buyer). If you are still having issues getting Venmo to be displayed, please open up an issue here: https://github.com/paypal/paypal-checkout-components/issues
