### ISSUE TITLE
[Bug] Props of style in interface `PayPalMessagesComponentOptions` is missing.

### ISSUE THREAD

**Issue by luffy84217** [paypal/paypal-js#165]
### 🐞 Describe the Bug

The props of style in interface `PayPalMessagesComponentOptions` is missing.

### 🔬 Minimal Reproduction

Running the following code:
```typescript
try {
    paypal = await loadScript({
        'client-id': 'YOUR_CLIENT_ID',
       '"data-client-token': 'YOUR_CLIENT_TOKEN',
    });
  } catch (error) {
    console.error('failed to load the PayPal JS SDK script', error);
  }

  if (paypal) {
    const options = {
        logo: {
            type: 'primary',
            position: 'left',
        },
        text: {
            color: 'black',
            align: 'left',
            size: 12
        },
    };
    try {
      await paypal.Messages(options).render('YOUR_MESSAGE_CONTAINER_ID');
    } catch (error) {
      console.error('failed to render the PayPal Buttons', error);
    }
  }
```

### 😕 Actual Behavior

By following the instruction from [Customize Pay Later messages](https://developer.paypal.com/docs/checkout/pay-later/us/integrate/customize-messages/)
I tried typing the code above, but Typescript says:

[messages.d.ts(4, 5)](https://github.com/paypal/paypal-js/blob/main/types/components/messages.d.ts#L4): The expected type comes from property 'style' which is declared here on type 'PayPalMessagesComponentOptions'

### 🤔 Expected Behavior

Error TS2332(typing error) shouldn't happen.

### 🌍 Environment

-   Node.js/npm: - 16.13.2/8.1.2
-   OS: - Windows 10 Home build 19042.1466
-   Browser: - Chrome/Edge

**Comment by gregjopa** [comment]
Thanks for fixing this @luffy84217!
