### ISSUE TITLE
Donate Button Amount

### ISSUE THREAD

**Issue by sgurin** [paypal/paypal-js#205]
### 🚀 Feature Proposal

It would be convenient to have the functionality to set amount for Donation button via Donation SDK. Now configuration of amount available only from portal.

### Motivation

In some system user has already predefined amount for donate and he should set amount the second time inside the PayPal Popup

### Example

It could be like an option **amount:**
![image](https://user-images.githubusercontent.com/25930200/159109482-cea851bb-8d7a-4683-ab38-83a34928c467.png)

**Comment by sgurin** [comment]
bump

**Comment by Basheer-alsyani** [comment]
VR8649ZEEG4UL
