### ISSUE TITLE
[Bug] Missing / incorrect typescript definitions

### ISSUE THREAD

**Issue by asmiller** [paypal/paypal-js#216]
### 🐞 Describe the Bug

There are several missing / incorrect types in Typescript definitions

### 🔬 Minimal Reproduction

* `OnApproveActions` is missing `get` and `patch` functions - needed to retrieve order data without capturing / authorizing
* `Payer` has an incorrect type for `phone` - the return value has a `phone_type` and `national_number` as a sub-property of `phone_number` object, but this library just has `phone_number` as a string: https://developer.paypal.com/docs/api/orders/v2/#definition-payer
* `ShippingInfo` does not include `options`, to pass shipping rates: https://developer.paypal.com/docs/checkout/standard/customize/shipping-options/

### 😕 Actual Behavior

Typescript throws warnings that types are incorrect, but the defined types leads to errors in the browser and missing functionality

### 🤔 Expected Behavior

Types should match the interfaces outlined in documentation

### 🌍 Environment

-   Typescript v4

**Comment by asmiller** [comment]
Additional issue: the `OnShippingChangeActions` `patch` function has no body. It should take an array of patch operations, as outlined here https://developer.paypal.com/docs/checkout/standard/customize/shipping-options/#link-shippingcallbackwithshippingoptions

**Comment by gregjopa** [comment]
Hi @asmiller thanks for the bug report with the TypeScript types. I agree with fixing these. Would you be up for sending a PR with a fix? We are always looking for more open-source contributors.

**Comment by MidnightDesign** [comment]
> @asmiller don't worry about the PR. @borodovisin already has an open PR for it! #217

@gregjopa That PR didn't include a type for the [`patch()` argument](https://github.com/paypal/paypal-js/blob/963aed995062eb72a1542b7b76a1e92cd3d9f732/types/components/buttons.d.ts#LL103C16-L103C16)
