### ISSUE TITLE
[Question] Return url ignored

### ISSUE THREAD

**Issue by realtebo** [paypal/paypal-js#238]
### 🐞 Describe the Bug

I am using `return_url` to bring user to a new page after order is completed.
It is simply not working

### 🔬 Minimal Reproduction

     paypal.Buttons({
            style: {
                "layout": "horizontal",
                "shape" : "rect",
                "tagline": "false",
                "label" : "checkout",
            } ,
            createOrder: function (data, actions) {
                // Set up the transaction
                return actions.order.create({
                    application_context: {
                        brand_name: "Demo Shop",
                        shipping_preference: "NO_SHIPPING",
                        return_url: '<?= (isset($_SERVER['HTTPS']) ? "https://" : "http://").   $_SERVER['HTTP_HOST'] . "/order-ok.php" ?>',
                        user_action: "PAY_NOW",
                    },
                    purchase_units: [{
                        referenmce_id: "mirkos_<?=time()?>",
                        description: "Ordine #bla bla 12",
                        soft_descriptor: "Soft_#<?=time()?>",
                        amount: {
                            value: '0.04'
                        }
                    }]
                });
            },

        })
        .render('#paypal-button-container');

### 😕 Actual Behavior

User can pay, but simply the popup disappear

### 🤔 Expected Behavior

After paying, I expected popup will close and the browser redirected user to a new page

### 🌍 Environment

-   Node.js/npm: - node v.14.19.1
-   OS: - indifferent, both windows and debian 10
-   Browser: - indifferent

### ➕ Additional Context

Nothing to add for me, now

**Comment by borodovisin** [comment]
Hi @realtebo, to accomplish the redirect after the client approved the payment transaction, you can use the `onApprove`
 callback and make the exact same idea. 

Here is an example:
```
onApprove: function (data, actions) {
    return actions.order.capture().then((orderData) => {
        window.location.href = "here the page you want to redirect";
    });
},
```

With the example above you guarantee the page will redirect after the client finishes the payment process.

**Comment by realtebo** [comment]
so what's the purpose of `return_url` ?

I was supposing to go to different pages if success or if failed, to update order status or warn user of the problem before returning to the order. My webapp is actually 100% php.
