### ISSUE TITLE
[Bug] PayPalMessagesComponentOptions not up to date

### ISSUE THREAD

**Issue by CoderBrad** [paypal/paypal-js#269]
### 🐞 Describe the Bug

The current PayPalMessagesComponentOptions does not match the documentation found [in the sdk docs](https://developer.paypal.com/docs/checkout/pay-later/us/integrate/reference/#link-messageconfigurationobject).

### 🔬 Minimal Reproduction

Compare current type to the docs.

### 😕 Actual Behavior

Current type is missing options mentioned in the docs.

### 🤔 Expected Behavior

To be able to reference options present in the docs.

### 🌍 Environment

N/A

**Comment by gregjopa** [comment]
This was resolved in #274
