### ISSUE TITLE
[Feature] How to test failed transactions?

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [paypal/paypal-js#273]
### 🚀 An easy way to test failed transaction. Right now it seems not to be possible?

Basically the answer to this question: https://stackoverflow.com/questions/73150831/how-to-test-failed-transactions-with-the-paypal-js-sdk

### Motivation

Testing failed payment paths is crucial to any integration. It is not understandable, that there appears to be no easy way to do it with paypal.

### Example

It should be something very straight foreward:

1. Login to a sandbox test account
2. Use a certain card
3. get 100% an error corresponding to live errors

**Comment by jshawl** [comment]
This page lists cards and various error scenarios if paying with a credit card: https://developer.paypal.com/tools/sandbox/card-testing/#link-simulatecarderrorscenarios

This page lists other ways to trigger errors for payments that do not ask the buyer to enter a credit card: https://developer.paypal.com/tools/sandbox/negative-testing/request-headers/#link-enablenegativetesting

We also have a public example here: https://github.com/paypal-examples/docs-examples/blob/main/standard-integration/server/server.js#L72-L76 

Thanks and feel free to open a new issue if you have any additional questions.
