### ISSUE TITLE
[Bug] Load error 400

### ISSUE THREAD

**Issue by Davide33IT** [paypal/paypal-js#278]
### 🐞 Describe the Bug

From today, the Paypal JS script has stopped to work, the call fails with this error: net::ERR_ABORTED 400

This is the request URL that my site made: https://www.paypal.com/sdk/js?client-id=MY_CLIENT_ID&vault=true&intent=subscription

The script stopped working today, until yesterday it worked.

I have tryed to cancel cookie and cache but the problem is not solved.

### 🌍 Environment

-   Node.js/npm: -
-   OS: Windows 11
-   Browser: Chrome

**Comment by Davide33IT** [comment]
Edit: After a few F5 browsers, the problem disappeared, this is very strange.

**Comment by gregjopa** [comment]
Hi @Davide33IT we had a brief outage this morning in the sandbox environment. Sorry for the trouble. It has been resolved.
