### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'render')

### ISSUE THREAD

**Issue by tengkuzulfadli** [paypal/paypal-js#288]
### 🐞 Describe the Bug

Cannot read properties of undefined (reading 'render') in React js

### 🔬 Minimal Reproduction

Here is the code sandbox : https://codesandbox.io/s/react-paypal-with-paypal-paypal-js-package-z2xlnr?file=/src/App.js

### 😕 Actual Behavior

When I place clientId to get paypal up and running, I got an error message on console

### 🤔 Expected Behavior

It should be able to recognise render and behave as expected

### 🌍 Environment

-   Node.js/npm: - 16.17.0 LTS
-   OS: - Windows 10
-   Browser: - Chrome

### ➕ Additional Context

I've got the same issue with @paypal/react-paypal-js npm package where React skipped hostedFields for card fields

here is screenshot of the error:

![Screenshot 2022-09-15 141707](https://user-images.githubusercontent.com/62935899/190314024-402030ef-2dcd-4adc-8c42-6cbbb2e45ae2.png)

**Comment by gregjopa** [comment]
I believe we were able to resolve this problem in https://github.com/paypal/react-paypal-js/issues/305. Closing this out.
