### ISSUE TITLE
[Bug] Bug report: TOKEN_FAILURE during subscription order creation

### ISSUE THREAD

**Issue by ArtemFokin** [paypal/paypal-js#297]
### 🐞 Describe the Bug

i'm getting errors with message: TOKEN_FAILURE  when trying create order with subscription. 
Previously everything works well.
I've also tried to create subscription from postman api and visit APPROVE link but got error message on sandbox.paypal.com
'Things don't appear to be working at the moment. Please try again later.'
I've also created a subscription button in paypal editor and tried put piece of code to codepen and got same error(TOKEN_FAILURE)

### 🔬 Minimal Reproduction
create account in sandbox, create product, create plan with this product, copy code and paste in codepen
[https://codepen.io/Artem122/pen/vYrOeqZ](https://codepen.io/Artem122/pen/vYrOeqZ)

### 🌍 Environment

-   Node.js/npm: - 18
-   OS: - macOS
-   Browser: - Chrome

**Comment by Davide33IT** [comment]
Same issue here, any solution?

**Comment by workmail20** [comment]
+1, Same issue

**Comment by cdmavani** [comment]
Still it's not resolved. Same Issue with subscription for sandbox. 
Token Failure error for below URL :
https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/xxxxxxxxx/cartid

**Comment by MTGPROD** [comment]
I knew it !! I have the same error, everything worked well since these days.

**Comment by gregjopa** [comment]
Hi everyone, this token failure issue with the PayPal Subscriptions Button in the PayPal sandbox environment is resolved. Sorry for the inconvenience. I'm going to close this out. Feel free to open a new issue if you are still experiencing problems.
