### ISSUE TITLE
[Feature] Phone Number from Order Capture

### ISSUE THREAD

**Issue by Lucien950** [paypal/paypal-js#328]
### 🚀 Feature Proposal
Order capture also contains phone number.

### Motivation
The form requires the submission of a phone number, amongst other fields of personal information. It would require another form to get phone number, which is bad for UX.

### Example
```js
onApprove: async function(data, actions) {
    const orderInfo = await actions.order.capture()
    //orderInfo.payer.phone_number or orderInfo.purchase_units[0].shipping.phone_number
}
```

**Comment by gregjopa** [comment]
The buyer's phone number is considered sensitive data which we cannot expose. Due to this reason, the buyer will always have to enter phone number into the inline guest credit card form.

**Comment by Anemia88** [comment]
> 

7831157993
