### ISSUE TITLE
[Feature Request] Set currency on button click

### ISSUE THREAD

**Issue by GregSmith92** [paypal/paypal-js#35]
If this is already possibe with a few minor tweaks, I do apologise.

### 🚀 Feature Proposal
Reload script on paypal button click so that a new currency can be passed correctly to the sdk

### Motivation

It is very awkward to have more than one paypal button on a page which goes to a checkout for different currencies.
This error is a cummon occurance without tedious workarounds:

`Expected currency from order api call to be GBP, got AUD. Please ensure you are passing currency=AUD to the sdk url`

This thread highlights the issue: 
https://github.com/paypal/paypal-checkout-components/issues/1180

**Comment by gregjopa** [comment]
Hi @GregSmith92, thanks for opening up this feature request. Can you share a demo html page or a mockup of what you'd like to accomplish with having multiple paypal buttons rendered using different currencies? We'd like to better understand this UX flow.

> Reload script on paypal button click so that a new currency can be passed correctly to the sdk

The current behavior requires settings a single currency when loading the script. When you have multiple paypal buttons on a page, they will all share this same currency (and other settings defined by the query params). We do have this example page for reloading the currency based on the form selection: https://github.com/paypal/paypal-js/blob/main/e2e-tests/reload-script/index.html

<img width="1032" alt="reload-demo-screenshot" src="https://user-images.githubusercontent.com/534034/94031473-80678600-fd84-11ea-9a23-d201f4c3c1af.png">

**Comment by GregSmith92** [comment]
Thanks for the response @gregjopa 

For a marketplace where users are selling in multiple currencies, and therefore buyers need to purchase in multiple currencies, we have decided to split out items in the cart by currency, providing each with a button to checkout for the given currency. The design on the page is quite sprawling, but imagine above the screenshot is a group of items being sold in GBP

I had just seen the demo you talk about. Ideally I would like to reload the script on the PayPal button click, as the currency is only selected at this point.

<img width="1135" alt="Screenshot 2020-09-23 at 16 23 06" src="https://user-images.githubusercontent.com/48311414/94033741-2f25b980-fdb9-11ea-9722-5fb129fb9048.png">

**Comment by gregjopa** [comment]
Thanks for sharing the mockup @GregSmith92! 

As a work around to match the requirements in the mockup, what do you think about using the scroll position to conditionally load and render the appropriate paypal button on the long shopping cart page? Here's an example using Intersection Observer to accomplish this: https://github.com/paypal/paypal-js/compare/reload-currency-scroll-position-demo

![reload-on-scroll-position](https://user-images.githubusercontent.com/534034/94046017-bc571700-fd95-11ea-8fa1-3acbdc1963d0.gif)

### Design Considerations 

It looks like the mock only shows the PayPal button for each currency and it doesn't show any other [funding sources](https://developer.paypal.com/docs/checkout/integration-features/standalone-buttons/#funding-sources). Currency is used to help determine which funding sources the buyer is eligible for. Your design isn't taking advantage of these other paypal features like offering a credit option. These additional funding sources improve checkout conversion so it may be worth sharing that with your team and rethinking the UX of shopping cart page.

**Comment by GregSmith92** [comment]
That is a seriously clever solution 👏

I have added it and it is rendering the PayPal button again with with the correct currency in the script as demonstrated. 

Unfortunately however, the issue is still persisiting in a slightly different way. When I go to checkout on the GBP button I still get the below error in the console, even though I can see in the inspector that the only sdk script on the page has the correct currency (before this wasn't correct), GBP. The AUD button, which is below, will go to checkout fine. Before, it was the first currency that could go to checkout, the rest would have a similar error. 🤔

<img width="1486" alt="Screenshot 2020-09-23 at 20 03 34" src="https://user-images.githubusercontent.com/48311414/94057861-1f699d80-fdd8-11ea-9e7b-7d4d7d650e7f.png">

**Comment by GregSmith92** [comment]
This error was due to my own faults in the JS file. Your solution is very elegant and works perfectly. I am very greatful 🙏🙏🙏

**Comment by gregjopa** [comment]
@GregSmith92 that's great to hear! Thank you for the kind words. I'm glad things are working on your end. I'm going to close this one out.
