### ISSUE TITLE
[Question] I encountered a cross-origin issue

### ISSUE THREAD

**Issue by nicolas-tesla-x** [paypal/paypal-js#363]
### 🐞 Describe the Bug

I encountered a cross-origin issue while using this library because our website has set the headers `Cross-Origin-Opener-Policy: same-origin` and `Cross-Origin-Embedder-Policy: require-corp`. Could you please advise on how to resolve this issue?

### 🔬 Minimal Reproduction
```javascript
import { loadScript } from '@paypal/paypal-js';

const paypal = await loadScript({
  'client-id': res.client_id,
  'data-client-token': res.client_token,
});
```

### 😕 Actual Behavior
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/25948904/234446995-c1a06703-367d-430c-a78e-0b10d5c9e813.png">

### 🤔 Expected Behavior
loads normally.

### 🌍 Environment

-   Node.js/npm: Node v18.15.0 / npm v9.5.0
-   OS: MacOS
-   Browser:  Chrome 112.0.5615.137

**Comment by Anemia88** [comment]
Error

**Comment by renzhao1113** [comment]
> Error

@Anemia88 I don't see what you mean

**Comment by westeezy** [comment]
The `requires-corp` and `same-origin` headers you set would block the paypal.com domain from being able to load scripts. There is no fix on our end for this as you specifically only scripts from your own origin  and we don't allow self hosting the script at this time.
