### ISSUE TITLE
Working in a webworker

### ISSUE THREAD

**Issue by AbdealiLoKo** [paypal/paypal-js#373]
### 🚀 Feature Proposal

When I try to use this library in a web worker - it does not work and returns null

### Motivation

I am trying to initiate a payment in wix velo - which allows me to run scripts only in web workers

**Comment by wsbrunson** [comment]
hi @AbdealiLoKo unfortunately our JS SDK will not work in a web worker environment. It was specifically written to work in the context of a web page
