### ISSUE TITLE
[Feature] Feature request Organize your API's

### ISSUE THREAD

**Issue by lantos1618** [paypal/paypal-js#374]
### 🚀 Feature Proposal

I would like to propose the organization and consolidation of PayPal's JavaScript APIs. Currently, finding the appropriate API or SDK for a specific task is challenging due to the lack of a clear and unified structure.

### Motivation

The current organization of PayPal's JavaScript APIs and SDKs is fragmented across multiple repositories, such as:

- [paypal-js](https://github.com/paypal/paypal-js)
- [paypal-sdk-client](https://github.com/paypal/paypal-sdk-client)
- [paypal-checkout-components](https://github.com/paypal/paypal-checkout-components)
- [react-paypal-js](https://github.com/paypal/react-paypal-js)
- [Payouts-NodeJS-SDK](https://github.com/paypal/Payouts-NodeJS-SDK)
- [Checkout-NodeJS-SDK](https://github.com/paypal/Checkout-NodeJS-SDK)
- [paypal-sdk-constants](https://github.com/paypal/paypal-sdk-constants)
- [paypal-smart-payment-buttons](https://github.com/paypal/paypal-smart-payment-buttons)
- [paypal-common-components](https://github.com/paypal/paypal-common-components)
- [paypal-funding-components](https://github.com/paypal/paypal-funding-components)
- [paypal-messaging-components](https://github.com/paypal/paypal-messaging-components)

While these repositories all serve important functions, it's difficult for developers to navigate through them and find the exact resources they need. In addition, the [PayPal Developer page](https://developer.paypal.com/sdk/js/configuration/) does not provide clear instructions on how to execute server-side checkouts.

By organizing and consolidating the APIs, developers will be able to find and utilize the PayPal JavaScript resources more efficiently, leading to a better developer experience and potentially increased usage of PayPal's services.

### Example

One way to implement this feature could be to create a central repository (or directory within an existing repository) that links to all of the JavaScript APIs and SDKs. This central repository could contain:

- A brief description of each API or SDK.
- Links to the relevant GitHub repositories or documentation.
- Sample code snippets or usage examples where applicable.
- A tutorial or guide for server-side checkouts.

The ideal situation would be to have the following example repositories being linked on the official [PayPal Developer page](https://developer.paypal.com/sdk/js/configuration/).
- ClientSide Only (pure JS) 
- ClientSide with ReactJS (Typescript)
- ClientSide with ReactJS (Typescript) and Backend express or NextJS checkout validation (Typescript) 

**I think having a NextJS example would be a significant increase to developer experience** 

This approach would make it significantly easier for developers to find the appropriate resources, understand their purposes, and learn how to use them effectively.

**Comment by lantos1618** [comment]
also possibly including an official sequence diagram to help developer understand the process flow of the payment systems  


Something like this?
```mermaid
sequenceDiagram
    participant F as Frontend
    participant P as PayPal API
    participant B as Backend
    F->>P: Initialize checkout (Create payment)
    P-->>F: Return paymentID
    F->>B: Send paymentID
    B->>P: Execute payment
    P-->>B: Return payment status
    B->>F: Send payment status
    F->>F: Update UI based on payment status
```

**Comment by lantos1618** [comment]
Also there should be clarification around using the Braintree api.

[Paypal JS sdk](https://developer.paypal.com/sdk/js/)

Contains a graphql api by braintree. Do you need a braintree account to use this or can you use the braintree api with ONLY paypal credentials

**Comment by wsbrunson** [comment]
hi @lantos1618, thank you for the suggestions!

We agree with a lot of your points and are working on revamping PayPal's open source repos, examples, and developer documentation.

Definitely watch this space and our developer blog for more updates! https://developer.paypal.com/community/blog/

Also, the latest version of the Standard Integration guide now includes a sequence diagram: https://developer.paypal.com/docs/checkout/standard/integrate/#link-howitworks
