### ISSUE TITLE
[Bug] Bug report

### ISSUE THREAD

**Issue by TheThirdRace** [paypal/paypal-js#382]
### 🐞 Describe the Bug

Since version `6.0` breaking change for query parameter from kebab to camel case, ex: `client-id` => `clientId`, I receive `400 Bad Request` when passed the info to `PayPalScriptProvider` from `react-paypal-js` package.

When passing the keys in kebab case to `PayPalScriptProvider`, it works just fine...

I don't know if I should have opened this in this package or in `react-paypal-js`. Either way, the integration with React wasn't tested when this breaking change was made.

### 🔬 Minimal Reproduction

It's pretty straightforward, the React integration was not adjusted after the breaking change from `paypal-js` package. No need for a reproduction.

### 😕 Actual Behavior

I get bad request in the network manager:

```text
// react-paypal-js.js:520 
GET https://www.paypal.com/sdk/js?clientId=xxxxxxxxxxxxxxxxxxxx&integrationDate=2021-12-24 net::ERR_ABORTED 400
```

*I hid the client id on purpose, it's of no consequences here

### 🤔 Expected Behavior

Passing camel case keys like `clientId` to `PayPalScriptProvider` should work.

### 🌍 Environment

-   Node.js/npm: -
-   OS: -
-   Browser: -

**Comment by gregjopa** [comment]
react-paypal-js has been updated to use the latest version of paypal-js. Closing this out.
