### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by mstuart** [paypal/paypal-js#39]
This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

**Comment by ReazerDev** [comment]
Hi, I'm interested in this. Never made typings for ts, sounds interesting!

**Comment by claeusdev** [comment]
Ah @ReazerDev beat me to it. If you need an extra hand lemme know.

**Comment by mstuart** [comment]
No worries @claeusdev! If you're wanting to hack around w/ TypeScript, there are some other similar ones under these repos too! https://github.com/paypal/hacktoberfest/blob/main/README.md#repos

**Comment by ReazerDev** [comment]
Wait, am I too eligible to get the socks?^^ I'm asking since I don't commit anything to this repo, but to DefinitelyTyped

**Comment by mstuart** [comment]
@ReazerDev No problem! When you commit it to DefinitelyTyped, can you drop the link here?

**Comment by ReazerDev** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48454

**Comment by ReazerDev** [comment]
Has been merged :)

**Comment by mstuart** [comment]
@ReazerDev wow, that was really fast 😸  Thanks! We have you down for some fancy socks. Have fun hacking :)

**Comment by ReazerDev** [comment]
Nice :) Was a lot of fun, thank you. You too have fun^^

**Comment by ReazerDev** [comment]
Am I getting an email regarding shipping information?

**Comment by mstuart** [comment]
I was thinking the same thing. I'm not sure how to get your contact info. We probably should've included a google form or thought that through.

Can you add your email to your GitHub profile real quick? Open to other ideas too. Or maybe I can DM you on Twitter or another way? Hmm... 🤔

**Comment by ReazerDev** [comment]
My Twitter is: Reazer_Dev

**Comment by gregjopa** [comment]
@ReazerDev thanks so much for adding types for paypal-js to DefinitelyTyped! 👏 

I was reviewing the PR and noticed a minor issue. The public api for paypal-js v1 is a single function `loadScript()` and a string attribute named `version`. The functions in utils.js are not publicly exported and should be removed from [the typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/paypal__paypal-js/index.d.ts). I could see how this is confusing since the paypal-js project lacks an index.js that clearly defines what is publicly exported.

Would you be up for sending a follow up PR to DefinitelyTyped to remove the types for the private functions? The types files should look like this:
```js
// Type definitions for @paypal/paypal-js 1.0
// Project: https://github.com/paypal/paypal-js
// Definitions by: ReazerDev <https://github.com/ReazerDev>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export interface ScriptOptions {
  // options here
}

export function loadScript(options: ScriptOptions): Promise<any>;
export const version: string;
```

**Comment by ReazerDev** [comment]
> @ReazerDev thanks so much for adding types for paypal-js to DefinitelyTyped! 👏
> 
> I was reviewing the PR and noticed a minor issue. The public api for paypal-js v1 is a single function `loadScript()` and a string attribute named `version`. The functions in utils.js are not publicly exported and should be removed from [the typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/paypal__paypal-js/index.d.ts). I could see how this is confusing since the paypal-js project lacks an index.js that clearly defines what is publicly exported.
> 
> Would you be up for sending a follow up PR to DefinitelyTyped to remove the types for the private functions? The types files should look like this:
> 
> ```js
> // Type definitions for @paypal/paypal-js 1.0
> // Project: https://github.com/paypal/paypal-js
> // Definitions by: ReazerDev <https://github.com/ReazerDev>
> // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
> 
> export interface ScriptOptions {
>   // options here
> }
> 
> export function loadScript(options: ScriptOptions): Promise<any>;
> export const version: string;
> ```

Oh yes, of course! Will do once I'm home!

**Comment by gregjopa** [comment]
Awesome! Thanks @ReazerDev!

Also, thanks for documenting all the `scriptOptions`. I think you got almost all of them. Here's a list I have on my end of all the different available options. It's in React PropTypes, but it should help with identifying any missing ones.

```
        "buyer-country": PropTypes.string,
        "client-id": PropTypes.string.isRequired,
        commit: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
        components: PropTypes.string,
        currency: PropTypes.string,
        "data-csp-nonce": PropTypes.string,
        "data-order-id": PropTypes.string,
        "data-page-type": PropTypes.string,
        "data-partner-attribution-id": PropTypes.string,
        debug: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
        "disable-funding": PropTypes.string,
        "integration-date": PropTypes.string,
        intent: PropTypes.string,
        locale: PropTypes.string,
        "merchant-id": PropTypes.string,
        vault: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
```

**Comment by ReazerDev** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48513

**Comment by gregjopa** [comment]
Great improvements @ReazerDev! Thanks for taking care of this so quickly. I approved the PR and it looks like you can merge it whenever you're ready: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48513#issuecomment-703802557

**Comment by ReazerDev** [comment]
Yup merged it

**Comment by gregjopa** [comment]
Thanks again @ReazerDev. I verified the types locally by installing `@types/paypal__paypal-js` and it works great 😄

**Comment by ReazerDev** [comment]
Great! Was fun working on it!
