### ISSUE TITLE
How to add `PayPal-Request-Id` header to button?

### ISSUE THREAD

**Issue by olfek** [paypal/paypal-js#390]
Hello,

How do I add the `PayPal-Request-Id` mentioned here: https://developer.paypal.com/api/rest/reference/idempotency
to:

```
paypal.Buttons({

    createSubscription(data, actions)
    {
        return actions.subscription.create({
            'plan_id': '<PLAN_ID>'
        });
    },

    onApprove(data)
    {
        alert('You have successfully created subscription ' + data.subscriptionID);
    }

}).render('#paypal-button-container');
```

https://developer.paypal.com/docs/subscriptions/integrate/#link-createpaymentbutton
https://developer.paypal.com/sdk/js/reference/#createsubscription

**Comment by gregjopa** [comment]
Hi @olfek, my recommendation is to create the subscription on the server. That way you can pass the paypal-request-id with the api call and persist the subscriptionID and paypal-request-id together on your back-end. The `actions.subscription.*` helpers are only there for people that do not have server-side code. Ex:
```js
// create the subscription on your server and return the id https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create
paypal.Buttons({
    createSubscription: function() {
        return fetch('/your-server/subscription/create/', {
            method: 'post'
        }).then(function(res) {
            return res.json();
        }).then(function(subscriptionData) {
            return subscriptionData.id;
        });
    },
```

**Comment by wsbrunson** [comment]
hi @olfek, I'm going to go ahead and close this issue since your original question was answered. If you are still having problems with the sandbox environment, please don't hesitate    
to open a new issue. Thanks!
