### ISSUE TITLE
[Feature] Use GitHub Actions for CI

### ISSUE THREAD

**Issue by gregjopa** [paypal/paypal-js#41]
It would be great to use GitHub Actions for CI instead of travis. To resolve this issue, complete the following:
- replace the travis.yml file with a github action workflow that runs linting, tests, and the build. I think it would be just like the github action recently added to react-paypal-js: https://github.com/paypal/react-paypal-js/pull/33
- replace the travis ci badge in the readme with a github actions badge

**Comment by logesr** [comment]
I can take this up!
