### ISSUE TITLE
[Feature] PayPalButtonsComponent ts support

### ISSUE THREAD

**Issue by Mingo-233** [paypal/paypal-js#410]
### 🚀 Feature Proposal

I have found that the latest package version for PayPal.js is 6.0.1, where PayPalButtonsComponent has only three methods in its ts type. However, when I printed this object in the JS console, I found that it has many methods, but it was not found in the ts file. Are these methods unusable or were the ts type omitted and added?

### Motivation

Improve development efficiency

### Example

![image](https://github.com/paypal/paypal-js/assets/69039945/100e0eb1-7796-4c59-a03f-6fed87939597)
![image](https://github.com/paypal/paypal-js/assets/69039945/beb15fc7-4a07-4500-9791-681650cd45f1)

**Comment by wsbrunson** [comment]
hi @Mingo-233 some of these methods come from Zoid: https://github.com/krakenjs/zoid

They are available for use but we only recommend that developers use the ones we've defined in types when integrating with the PayPal JS SDK.
