### ISSUE TITLE
[Feature] array of strings should be allowed for `enable-funding` and `disable-funding`

### ISSUE THREAD

**Issue by CBoensel** [paypal/paypal-js#418]
### 🚀 Feature Proposal

Please allow an array of strings in the type definition where it makes sense. You currently get a type error in your ide, even though technically, it's supported. 

### Motivation

For parameters, where more than one value are likely to be entered (namely the ones in the headline), this makes sense, since it is 
(1) cleaner and more readable in the code of the merchant's client-side paypal integration and 
(2) it's supported already (see line 92 of [`utils.ts`](https://github.com/CBoensel/paypal-js/blob/main/src/utils.ts#L92)).

![grafik](https://github.com/paypal/paypal-js/assets/4338717/fca2266b-493b-45d3-876d-970852267e3c)

### Example

```js
paypal = await loadScript({
    clientId: "test",
    "disable-funding": ["card", "sepa", "giropay"]
});
```
would become a valid option on top of 

```js
paypal = await loadScript({
    clientId: "test",
    "disable-funding": "card,sepa,giropay"
});
```

**Comment by gregjopa** [comment]
Resolved by #419
