### ISSUE TITLE
 PayPalApplePayError: accountlifecycleserv responded with no legal_country_code field

### ISSUE THREAD

**Issue by lrencallado** [paypal/paypal-js#433]
### 🐞 Describe the Bug

I'm trying to integrate Apple Pay using PayPal SDK but I'm getting an error.

errorName: "APPLEPAY_CONFIG_ERROR"
message: "accountlifecycleserv responded with no legal_country_code field"
name: "PayPalApplePayError"
paypalDebugId: "f2001438ac1c3"

### 🔬 Minimal Reproduction

I'm following these steps https://developer.paypal.com/docs/checkout/apm/apple-pay/#link-howitworks

**Comment by Dimchykus** [comment]
Did you manage to fix it?
