### ISSUE TITLE
How to inject crossorigin="anonymous" in script tag when using loadScript

### ISSUE THREAD

**Issue by geekyshow1** [paypal/paypal-js#434]
I am using Nuxt 3 and @paypal/paypal-js Module below is my code and trying to figure out how can i inject crossorigin in the generated script tag.
We are trying to solve this issue https://github.com/Baroshem/nuxt-security/issues/255
```
<script setup>
import { loadScript } from '@paypal/paypal-js';
const paypalSdk = await loadScript({
    clientId: paypalClientID,
    currency: 'USD',
    disableFunding: 'card'
  });
  paypalSdk.Buttons({
    // Styling
    style: {
      layout: 'vertical',
      color: 'gold',
      shape: 'rect',
      label: 'buynow',
    },
    // Sets up the transaction when a payment button is clicked
    createOrder: async function (data, actions) {
      const { data: createdProductDetail } = await useFetch(api_url, 'POST', { 'slug': slug });
      return createdProductDetail.value.id;
    },
    // Finalize the transaction after payer approval
    onApprove: async function (data, actions) {
      const { data: orderData } = await useFetch(api_url + `${data.orderID}/capture/`, 'POST', { 'slug': slug });
      if (orderData.value.status === "COMPLETED") {
          return navigateTo('/success', { replace: true })
      }
    },
  }).render("#paypal-button-container");
}
</script>
<template>
  <div id="paypal-button-container"></div>
</template>
```

**Comment by drewangell** [comment]
I'm afraid I don't have time right this moment to dig into this more, but Bard seems to have provided an interesting reply that may help.  Please check this and let me know if it helps:  https://g.co/bard/share/236dcc242da3

If not I can dig more into this a little later.

**Comment by geekyshow1** [comment]
I truly appreciate your assistance so far. I've given the code a try based on your guidance, but it seems we might need to include the 'crossorigin' attribute in core coding of loadScript. I noticed features like 'currency' and 'disableFunding' are present, and adding 'crossorigin' might just be the missing piece.
I'm eagerly looking forward to your solution, and I'm confident that, with your expertise, we'll achieve the desired outcomes.

**Comment by gregjopa** [comment]
Hi @geekyshow1, thanks for filing this issue. We added support for the `crossorigin` attribute in the latest release (paypal-js@7.1.0). Please give it a try.
