### ISSUE TITLE
[Bug] CreateOrderRequestBody seems incorrectly typed

### ISSUE THREAD

**Issue by mikelpr** [paypal/paypal-js#436]
### 🐞 Describe the Bug
trying to get a grasp of what I can do I decided to use the CreateOrderRequestBody type for my body but I ran into the paypal backend actually rejecting the changes that were suggested

### 🔬 Minimal Reproduction
I had:
```
const body = {
          intent: 'CAPTURE',
          purchase_units: [
            {
              amount: {
                currency_code: 'USD',
                value: '10.00'
              }
            }
          ],
          payee: {
             email_address: '<redacted>'
          },
          payment_instruction: {
            disbursement_mode: 'INSTANT',
            platform_fees: [
              {
                amount: {
                  currency_code: 'USD',
                  value: '1.00'
                }
              }
            ]
          },
          payment_source: {
            paypal: {
              experience_context: {
                brand_name: 'brand',
                shipping_preference: 'NO_SHIPPING'
              }
            }
          }
        };
```

typing it with const body: CreateOrderRequestBody, it actually told me that payee and payment_instruction go in a purchase_unit object. moving payee up there I don't know what it does since it loads fine (but I didn't do the checkout), but moving payment_instruction to the purchase_unit object makes the server just reject the request, and you can see in the console Uncaught Error: Error: Expected an order id to be passed
    at https://www.sandbox.paypal.com/smart/buttons?style.layout=horizontal&style.color=gold&style.shape=r <snip>

also the experience_context object is just typed for cancel_url, return_url, and user_action. totally missing brand_name and shipping_preference

### 😕 Actual Behavior
following the typings, the server rejects the payload

### 🤔 Expected Behavior
the typings reflect what the paypal server wants

### 🌍 Environment

-   Node.js/npm: - v18.18.2
-   OS: - Fedora Linux 38
-   Browser: - Chrome 120

**Comment by gregjopa** [comment]
Hi @mikelpr, thanks for reporting this issue. We are actively working on using the new Open API 3.0 spec for auto-generating the types for the PayPal APIs in this repo. Here is the PR to track for this work: https://github.com/paypal/paypal-js/pull/443

**Comment by wsbrunson** [comment]
hi @mikelpr this work has merged, we are now using OpenAPI to generate TypeScript types for the Orders API. I'm going to close this issue, please open a new one though if you run into problems with the new types!
