### ISSUE TITLE
[Bug] Button background changes to blue when pending transaction

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [paypal/paypal-js#448]
### 🐞 Describe the Bug
Background behind the button becomes blue during transaction pending state (see animation below)

### 🔬 Minimal Reproduction

Click on PayPal button to get into transaction processing (pending) state

### 😕 Actual Behavior

![CleanShot+2024-01-10+at+23 12 48](https://github.com/paypal/paypal-js/assets/2766448/9fc536ec-df59-432c-9a72-180e399b4a88)

### 🤔 

Expected Behavior

Button background should not change during pending state

### 🌍 Environment

-   Node.js/pnpm: - 20.9.0 / 8.12.0
-   OS: Windows/MacOS
-   Browser: Chrome/Edge/Safari

### ➕ Additional Context

The issue started to appear after upgrade from v.7.0.3 to 8.0.0

The thick blue border can be seen when focus on the Paypal button.
The new paypal package version changed button focus styling while the page is pending.

![image](https://github.com/paypal/paypal-js/assets/2766448/ed021e1c-f758-49ce-89fc-99569a2672a0)

**Comment by BerlinChan** [comment]
I've tested the Paypal button on [the official demo page](https://developer.paypal.com/demo/Checkout/#/pattern/horizontal). The thick blue border is the official default `:focus` style. And there is no option to customize the style officially. Do we have?

![image](https://github.com/paypal/paypal-js/assets/14348629/4a5de035-8202-4097-939e-2e6925b41ccd)

**Comment by AndrewBogdanovTSS** [comment]
Is there any update regarding this issue?

**Comment by Bongdautay** [comment]
quaroibn1@gmail.com
