### ISSUE TITLE
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">   <input type="hidden" name="cmd" value="_s-xclick">   <input type="hidden" name="hosted_button_id" value="6RNT8A4HBBJRE">   <input type="image" src="https://www.paypalobjects.com/webstatic/en_US/i/btn/png/btn_buynow_107x26.png" alt="Buy Now">   <img alt="" src="https://paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"> </form>[Bug] Bug report

### ISSUE THREAD

**Issue by Skinny7seven7** [paypal/paypal-js#484]
### 🔬 Minimal Reproduction

Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

### 😕 Actual Behavior

A clear and concise description of what is happening. Please include console logs during the time of the issue, especially error messages.

### 🌍 Environment

-   Node.js/npm: -
-   OS: -
-   Browser: -

**Comment by ravishekhar** [comment]
Please contact Technical Support using https://developer.paypal.com/support/  for issues with the above button. 
This repository does not support the above integration type.
