### ISSUE TITLE
[Bug] Debit or Credit Card section not loading after click the button

### ISSUE THREAD

**Issue by pbojanczyk** [paypal/paypal-js#488]
### Library used

paypal-js

### 🐞 Describe the Bug

When clicking the Debit or Credit Card button too quickly after the page loads, the credit card page fails to load.  It's very intermittened but I can see that the error stems from a HTTP 400 error coming back from /smart/card-fields endpoint when the SDK tries to render the credit card iframe.  

This issue is reproducible on your demo checkout page here: https://developer.paypal.com/demo/checkout/#/pattern/validation

### 🔬 Minimal Reproduction

1. Navigate to https://developer.paypal.com/demo/checkout/#/pattern/validation
2. As soon as you see the black Debit or Credit Card button appear, click it

Please note that it doesn't happen all the time.  I often have to try multiple times before I'm able to reproduce it.

### 😕 Actual Behavior

Spinner appears and spins endlessly

### 🤔 Expected Behavior

Spinner should appear briefly while it loads the credit card form but then it should disappear and the form should be visible.

### 🌍 Environment

-   Node.js/npm: -
-   OS: - Windows
-   Browser: - Chrome (latest)

### ➕ Additional Context

I've attached a screenshot of the error happening on your official demo page.

![paypal-error](https://github.com/paypal/paypal-js/assets/14302673/dc6b5c9f-8052-4bea-a111-2eff50ac602c)

**Comment by geekdevs** [comment]
I have the same problem, it seems to be only happening on Sandbox account and is also country-specific. It started to appear consistently (also not on every test) about a month ago.

**Comment by hexluxiang** [comment]
> I have the same problem, it seems to be only happening on Sandbox account and is also country-specific. It started to appear consistently (although not on every test) about a month ago.我有同样的问题，它似乎只发生在沙盒帐户上，并且也是特定于国家/地区的。大约一个月前，它开始持续出现（尽管不是在每次测试中）。

We have also encountered the same problem. Do you have a good solution?

**Comment by hexluxiang** [comment]
> I have the same problem, it seems to be only happening on Sandbox account and is also country-specific. It started to appear consistently (although not on every test) about a month ago.我有同样的问题，它似乎只发生在沙盒帐户上，并且也是特定于国家/地区的。大约一个月前，它开始持续出现（尽管不是在每次测试中）。

We have also encountered the same problem. Do you have a good solution? Or reduce the probability of interface errors?

**Comment by wsbrunson** [comment]
We have an internal live issue tracking this bug, there is a team looking into the fix now. I'll update this ticket when the fix has been identified and again when it is deployed

**Comment by hexluxiang** [comment]
> We have an internal live issue tracking this bug, there is a team looking into the fix now. I'll update this ticket when the fix has been identified and again when it is deployed

Thank you for your reply. We look forward to receiving updates from the PayPal team regarding this issue.

**Comment by wsbrunson** [comment]
@pbojanczyk @hexluxiang This bug should be fixed
