### ISSUE TITLE
[Bug] buttons style shape & loadScript result

### ISSUE THREAD

**Issue by 21stc-09** [paypal/paypal-js#490]
### Library used
 paypal-js
version 8.0.2/8.0.5

### 🐞 Describe the Bug

1.function `loadScript` seems to return `PayPalNamespace` , but i cant use `CardFields`

2.There is no 'sharp' option for the shape field（buttons.d.ts/PayPalButtonsComponentOptions）, but it is in the [document](https://developer.paypal.com/sdk/js/reference/#link-shape), and 'sharp' option works.

### 😕 Actual Behavior
This is the result returned by loadScript
![17152358634222](https://github.com/paypal/paypal-js/assets/53696264/bbfaadcf-bca2-4569-b7cf-3a828b03c8f9)

### 🤔 Expected Behavior

1.The first problem I want it return the object with `CardFields`, then i can use  paypal && paypal.CardFields()
2.The second problem can be solve by ts-ignore,but i want to know whether you want to cancel the sharp option or just forget to update the type

### 🌍 Environment

-   Node.js/npm: v20.9.0 / 8.19.4
-   OS: Windows 10
-   Browser: Chrome 126.0.6452.3

**Comment by wsbrunson** [comment]
for 1., can you share the options you are providing to `loadScript`?

**Comment by 21stc-09** [comment]
> for 1., can you share the options you are providing to `loadScript`?

the first question is my mistake. our company account has not applied for `CardFields` payment yet.

**Comment by 21stc-09** [comment]
> 2. 绝对是一个错误，我们的董事会上实际上有一张票可以解决这个问题，但我们还没有得到解决。我会将此问题链接到该票证，因此一旦部署，他们将返回并更新此问题。

ok, thank you!

**Comment by 21stc-09** [comment]
@wsbrunson after our account get permission, we can show the cardfields, but i prefer `components` to  `overview` in the [doc](https://developer.paypal.com/sdk/js/reference/#link-overview).

when use the CardFields I meet a new question. 
After `CardFields.createOrder` get the order ID, Paypal-js auto request the interface `/v2/checkout/orders/xxx/confirm-payment-source`,
it return  `details[0].issue : PEKMISSION DEIED`, `name: HOT AUTHORIZED` , it seems i need to set TOKEN? but how can i set it token
![Uploading 企业微信截图_17182444667205.png…]()
