### ISSUE TITLE
CSP error for script-src

### ISSUE THREAD

**Issue by luminalpark** [paypal/paypal-js#493]
### Library used

paypal-js 8.0.5

### 🐞 Describe the Bug

During HostedFields validation I get the following in console:

"Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-<redacted>' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list"

**Comment by hanzoow** [comment]
im facing this ? any solutions
