### ISSUE TITLE
[BUG]: Paypal buttons not rendering

### ISSUE THREAD

**Issue by rash09** [paypal/paypal-js#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Have integrated paypal in my SPA react application and in the browser network can see the successful calls by paypal APIs, however, I don't see the buttons displayed on the page. below is the attached screenshot where the div wrapper block has empty class attribute, not sure if that is causing the display issue.

_Note: This react application is wrapped with Azure B2C authentication, not sure if that is blocking the buttons as I tested this integration with a simple react application and is working as expected._

### 😕 Current Behavior

When i load the page, paypal buttons are not visible on the page.

### 🤔 Expected Behavior

When i load the page , i need to view the paypal buttons

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  8.0.5     |
| Browser          |124.0.6367.118         |
| Operating System |   IOS  Ventura 13.6.6 (22G630)         |
```

### Relevant log output

![Uploading Screenshot 2024-05-05 at 9.40.56 PM.png…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by josephmarkus** [comment]
Same here

**Comment by naamhaiabdullah** [comment]
I am having the same issue. My website's pricing section renders three PayPal button under different plans, but only one renders unless I refresh. Here is the website: https://superdevpro.com

**Comment by wsbrunson** [comment]
@naamhaiabdullah all three showed up for me without a refresh. What browser are you using?

<img width="1317" alt="Screenshot 2024-06-24 at 17 46 14" src="https://github.com/paypal/paypal-js/assets/3527966/edb8a67e-5c45-4a4f-abef-d51b464f6963">

**Comment by naamhaiabdullah** [comment]
Hmmm, it's working on Chrome 126 (Stable) and Safari perfectly, the problem is with the Chrome 127 (Beta) I am using. 
You might need to open this issue with the Chrome team. I have tried clearing all types of cache from Chrome 127 (Beta), still the issue persists.

**Comment by naamhaiabdullah** [comment]
The issue is no longer happening in Chrome Beta 128 on MacOS Sonoma. Maybe you can safely close the issue.

**Comment by nam-truong-le** [comment]
I have the same issue, sdk is loaded but nothing is shown:

```typescript
const [{ isPending, isRejected, isInitial, isResolved }] = usePayPalScriptReducer();

  return (
    <>
      {isPending && <Typography>Loading payment method...</Typography>}
      {isRejected && <Typography>Failed to load payment method. Please try again later.</Typography>}
      {isInitial && <Typography>Loading payment method...</Typography>}
      {isResolved && <Typography>Payment method loaded.</Typography>}
      <PayPalButtons
```

`usePayPalScriptReducer` returns `isResolved=true` but nothing to see on the page:

<img width="673" alt="Bildschirmfoto 2024-09-24 um 01 26 34" src="https://github.com/user-attachments/assets/a92f3991-e7da-4083-a3e9-13c7ef688170">
