### ISSUE TITLE
[Bug] Incorrect types for `onShippingAddressChange`

### ISSUE THREAD

**Issue by GazzaHazza** [paypal/paypal-js#519]
### 🐞 Describe the Bug

There are several missing / incorrect types in Typescript for `onShippingAddressChange`

### 🔬 Minimal Reproduction

[OnShippingddressChange](https://github.com/paypal/paypal-js/blob/main/packages/paypal-js/types/components/buttons.d.ts#L171) is missing the `errors` object.
[Reject](https://github.com/paypal/paypal-js/blob/main/packages/paypal-js/types/components/buttons.d.ts#L199) function is missing argument type of `string`

Both are shown in [documentation](https://developer.paypal.com/sdk/js/reference/#link-onshippingaddresschange). 

😕 Actual Behavior
Typescript throws warnings that types are incorrect, but the defined types leads to errors in the browser and missing functionality

🤔 Expected Behavior
Types should match the interfaces outlined in documentation

🌍 Environment
Typescript v4

**Comment by Flysky12138** [comment]
bump
