### ISSUE TITLE
[Bug] Typescript warning: `resetOptions` cannot be used in dispatch type

### ISSUE THREAD

**Issue by TheMikeyRoss** [paypal/paypal-js#530]
### Library used

`react-paypal-js`

### 🐞 Describe the Bug

Typescript warning that `resetOptions` cannot be used as a dispatch type

![image](https://github.com/paypal/paypal-js/assets/46135573/9228852e-c28e-4a0e-b17b-23dc3d0adf36)

### 🔬 Minimal Reproduction

Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

### 😕 Actual Behavior

A clear and concise description of what is happening. Please include console logs during the time of the issue, especially error messages.

### 🌍 Environment

-   Node.js/npm: -
-   OS: -
-   Browser: -

**Comment by pablojsx** [comment]
Same happened, after renegerating the package-lock file.

**Comment by MeriDev** [comment]
TS warnings cleared out after doing this:
import {
  usePayPalScriptReducer,
  DISPATCH_ACTION
} from '@paypal/react-paypal-js';

 dispatch({
          type: DISPATCH_ACTION.RESET_OPTIONS,
          value: {
            clientId: paypal.clientId,
            currency: 'USD',
          },
        });

**Comment by SrichonBoon** [comment]
> Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please create a new issue with up-to-date information.
Why do you lock my account.?
