### ISSUE TITLE
[Question] Vue integration

### ISSUE THREAD

**Issue by ArchimedesW** [paypal/paypal-js#54]
When I use vue, the example is 

`paypal.Buttons.driver("vue", Vue)`

At this time, I cannot use style to set its style.

**Comment by gregjopa** [comment]
Hi @ArchimedesW, can you open up a bug report for the PayPal vue driver in [paypal-checkout-components](https://github.com/paypal/paypal-checkout-components/)? That's the repo we use to manage issues for code in the JS SDK.

As a workaround, are you able integrate into your Vue app with paypal-js without using the built-in drivers? Wondering if you could just render directly to a div (`window.paypal.Buttons().render('#buttons-container')` or use a ref.
