### ISSUE TITLE
[Bug] Getting 500 Unhandled api error in cartid API for subscriptions

### ISSUE THREAD

**Issue by shash61** [paypal/paypal-js#546]
### Library used

 react-paypal-js 
 
### Environment
Sandbox

### 🐞 On click of Paypal button, subscription is created, but cartId API is failing.

I have integrated with react-paypal-js and when i click on the button, subscription is created. But react-paypal internally calls cartId API just after subscription creation and it gives 500 status code. 
The error returned by cartId API looks like this. 
`{
    "ack": "error",
    "message": "Unhandled api error",
    "meta": {
        "calc": "f835959a4e741",
        "rlog": "rZJvnqaaQhLn%2FnmWT8cSUueWscmrtUHe5Y1Bd%2FeqyvyOTq66rSXAciiXRg7dClMl1o2iporwJbYz7mI0k8X%2B5rx9VK7gkS6f_190ed8d14e7"
    },
    "server": "p7AeaSvo5k6iOFKfqv3PYWqIYw7rNyNzts3hTHzKG8q1fD8L_Itt5G3qvxW_8Y6At7-SKpmWE9aeI5Sag3o899-8E5Sv365tysCbJmOz4YPAotHmjPwfZFmeZqRzXC1U8Hh_Q1YB7L-GVz_b4f2atBvn1qVqB52Poe6viPV9FlrLcOBGtberTWA41cTCe4ggu3uOYtf9GuK0qriCCDqt2Q0ZBA0KbvHhLDcMgc5LJFGyAOiDY0z-9KyX4NdLhm8UP_ae95bbCA_SkVKntEtPgBhcgWcHoqVwMVWS7hCu07QqelZCtYiLLG"
}`
This error came a week before too, but automatically got resolved on its own. This would be a problem for us to take it live while not knowing when and how this error occurs.

### 🔬 Minimal Reproduction

1. click on paypal button 
2. subscription is created successfully
3. cartid API is called, popup closes automatically giving 500 status code.

### 😕 Actual Behavior
1. clicking on paypal subscription button, subscription is created successfully, cartid API fails, popup closes.

### 🤔 Expected Behavior
1. clicking on paypal subscription button, user should be able to pay and activate their subscription on paypal.

### 🌍 Environment

-   Node.js/npm: - V14.15.1, 6.14.8
-   OS: - macOS
-   Browser: - chrome

### ➕ Additional Context
<img width="1671" alt="Screenshot 2024-07-26 at 11 28 07 AM" src="https://github.com/user-attachments/assets/c1e3f53f-5af2-47e9-a63e-f4289804f18b">

**Comment by shash61** [comment]
@wsbrunson can you please take a look at this, we couldn't move forward with this on Production as we don't know when this error occurs.

**Comment by yongjieYuan** [comment]
The same, I test subscription in sandbox after switched another account, it still has problem but checkout payment works well.

**Comment by omer8888** [comment]
im getting the same, yesterday it worked,
any idea what have change?

**Comment by orshemtov** [comment]
Im getting the same error, also yesterday worked 

Error: Api: /smart/api/billagmt/subscriptions/I-XXXXXXXXXXXX/cartid returned status code: 500 (Corr ID: f7...)

**Comment by omer8888** [comment]
i tweeted about it here, follow me to keep contact with similar issues
big mess, i spent 5h tring figur out whats changed
anyone have solution?
https://x.com/omer_naim/status/1816811239705837886

**Comment by wsbrunson** [comment]
hi all, can anyone attach a Correlation ID of the failed call? you should see it in the response headers as `PayPal-Correlation-Id`

**Comment by ItsJustTomDev** [comment]
> hi all, can anyone attach a Correlation ID of the failed call? you should see it in the response headers as `PayPal-Correlation-Id`

Paypal-Debug-Id:
f12373139ba59

Couldnt find "PayPal-Correlation-Id" in the headers but I found this one, also in the response there is a "meta" object with "calc" field which value is: f780042cf159b

url: https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/I-7NYEK3A0CN5L/cartid

**Comment by acouette** [comment]
@wsbrunson : 
Same here, not `PayPal-Correlation-Id` but I have
`Paypal-Debug-Id: f303630395a85`

**Comment by rohit-splashmath** [comment]
@wsbrunson 

Paypal-Debug-Id: `f872515447000`

Request URL: `https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/I-GLW1F9FML66E/cartid`

**Comment by wsbrunson** [comment]
I'm going to create an internal bug ticket and get our API team involved. I'll keep you updated on the status.

thank you all for your reports

**Comment by LuisBizocial** [comment]
@wsbrunson 
 
The same thing is happening to me.

When i click on the button, subscription is created. But paypal internally calls cartId API just after subscription creation and it gives 500 status code.

Paypal Event Log:

Date and time | 7/26/24, 6:36 AM
Request path | /v1/billing/subscriptions
Status | 201
Debug ID | f98901529688e
Issue | N/A
Description | N/A
Resource ID | N/A

RESPONSE:
{
  "status": "APPROVAL_PENDING",
  "id": "I-TR8D3FTAN7A3",
  "create_time": "2024-07-26T13:36:37Z",
  "links": [
    {
      "href": "https://www.sandbox.paypal.com/webapps/billing/subscriptions?ba_token=BA-03L76365M2689225H",
      "rel": "approve",
      "method": "GET"
    },
    {
      "href": "https://www.sandbox.paypal.com/v1/billing/subscriptions/I-TR8D3FTAN7A3",
      "rel": "edit",
      "method": "PATCH"
    },
    {
      "href": "https://www.sandbox.paypal.com/v1/billing/subscriptions/I-TR8D3FTAN7A3",
      "rel": "self",
      "method": "GET"
    }
  ]
}


Front-end response error:
Api: /smart/api/billagmt/subscriptions/I-5U8F9YLEUSDA/cartid returned status code: 500 (Corr ID: f662736d2ef56)

{"ack":"error","message":"Unhandled api error","meta":{"calc":"f662736d2ef56","rlog":"rZJvnqaaQhLn%2FnmWT8cSUueWscmrtUHe5Y1Bd%2FeqyvyOTq66rSXAciiXRg7dClMl1o2iporwJbYz7mI0k8X%2B5rx9VK7gkS6f_190ef5a4540"},"server":"V8og602EktmL2jyVzChynMt0OergCaehedIMs3db1HvMCkqFkTMVyZFQgKAzcAiosmALt36yhWu8jdDz7hJJAnUVWP-f9yge-C59yF81g8_VvJjd70boBO88uDkhTAfs_Ir7hYUU-sqFE9jZysPvGHrUAtafHEWLTyTJSCa-qU4qYPfp55CUTpg5-FAsOi69GXCI0nHIaF1ywmzgvvTu4USEGS877uoiIQs5h-6pIDDK1IBGp_QZENLIVNWStmckXZmgKzIuxP4gzXvqixOB3fSsJFQWgJBW1bXmQTIqc3xJ13B0Wuop6G"}

**Comment by LuisGerar321** [comment]
I have the same problem

**Comment by bella-booking** [comment]
I have the same problem

**Comment by Spencer1119** [comment]
I would start my beta today. I'm having the same error. Window launches, fails, closes. 
![Screenshot 2024-07-26 at 12 41 29 PM](https://github.com/user-attachments/assets/ed045369-0384-478b-b83b-9f0bd8018c16)

**Comment by ConnectaCleaner** [comment]
I am dealing with the same error.

**Comment by Gera-The-Sniper** [comment]
I'm dealing with the same issue, hope it gets fixed soon

**Comment by MoonLightx03** [comment]
The same error, I test subscription in sandbox with javascript SDK

**Comment by ravishekhar** [comment]
Thanks everyone for your patience. This has been fixed now.

**Comment by omer8888** [comment]
Thank you!

**Comment by LuisGerar321** [comment]
Thanks!

**Comment by wsbrunson** [comment]
Hi all, the issue has been resolved.

Only sandbox was affected, there were no issues that we can see with the production environment.

Thanks again for all your reports!
