### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by zy598586050** [paypal/paypal-js#555]
"@paypal/paypal-js": "^8.1.0"

BUG-DEMO: https://github.com/zy598586050/paypal-bug

**Comment by gordonchanhk** [comment]
Regarding the JS error that happen when you are trying to run loadscript:
![Screenshot 2024-08-21 at 18 05 35](https://github.com/user-attachments/assets/94df4e79-a43b-4acd-8b0d-2187540b65b0)

As your dev lang is Vue, In your app.vue, <div id="paypal"> will form a JS object instance, which conflict with the paypal JS SDK paypal object instance.
![image](https://github.com/user-attachments/assets/5a1eedef-6868-4f74-81ac-49cfe7bb3e3c)

Change <div id="paypal"> to other id value, such as <div id="paypal-container"> and change corresponding reference can resolve the issue.
