### ISSUE TITLE
[Bug] Incompatible Client vs 3D secure Version.

### ISSUE THREAD

**Issue by chrisbeldam** [paypal/paypal-js#563]
### Library used

react-paypal-js (8.6.0)

### 🐞 Describe the Bug

We're using Braintree Web - 3.107.1 to take card payments. However when using React-Paypal-Js, the scripts being loaded are always for Braintree 3.84.0 which is causing a conflict when attempting to make payments. I have removed React-PayPal-JS from our project and payments are successful and no scripts load for 3.84.0. 

### 🤔 Expected Behavior

React-PayPal JS to use the same version of Braintree Web or provide an option to specify which version we're using

### 🌍 Environment

-   Node.js/npm: - 22.2.0
-   OS: - Mac OS 14.6.1
-   Browser: - Chrome 128.0.6613.121

### ➕ Additional Context

<img width="644" alt="Screenshot 2024-09-13 at 16 35 54" src="https://github.com/user-attachments/assets/aaa2ed78-9e8a-4097-aa08-4548bf917c56">

<img width="1096" alt="Screenshot 2024-09-13 at 11 33 47" src="https://github.com/user-attachments/assets/05061ba5-8678-42b2-a0f8-def0efd887c4">

**Comment by chrisbeldam** [comment]
I see the version of Braintree is hard-coded. This is causing us quite a few problems. Is it likely to be updated any time soon>

![Screenshot 2024-09-16 at 09 46 57](https://github.com/user-attachments/assets/2ff01b26-6d26-49c5-9ce8-be77871daf5c)

**Comment by shahfaizanali** [comment]
I am having same issue
