### ISSUE TITLE
locales behavior is different

### ISSUE THREAD

**Issue by antoniopacheco** [paypal/paypal-js#58]
I do not think this is a bug of this specific library but for the script:
https://www.paypal.com/sdk/js
however I did not find any place to submit this bug.

### 🐞 Describe the Bug
The normal behavior for the smart buttons is :
none of them forces of the users to create an account
"Debit or Credit Card" button opens the form in the same page

however when you specify a locale outside of US for example es_MX 
all of the buttons will open a modal and will force the user to create an account

### 🔬 Minimal Reproduction
go to: 
https://developer.paypal.com/demo/checkout/#/pattern/server

test the behavior without changing anything.
notice that buttons won't force you to create an account and
"Debit or Credit Card" button opens the form in the same page

now change the script src to 
 `<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD&locale=es_MX"></script>`

### 😕 Actual Behavior
  all buttons force the user to create an account
 "Debit or Credit Card" opens in a modal.

### 🤔 Expected Behavior
Using different locales shouldn't force the user to create a Paypal account (this is the most important one)
Debit or credit card button should open within the page (like when no locale is specified or a US locale)

### 🌍 Environment

- Node.js/npm: -
- OS: -
- Browser: -

**Comment by gregjopa** [comment]
Hi @antoniopacheco, please report this locale issue in the [checkout-components repo](https://github.com/paypal/paypal-checkout-components/). That's the best place to report JS SDK issues.
