### ISSUE TITLE
[Bug] Typescript missing types for OnApproveOrderActions.actions

### ISSUE THREAD

**Issue by antoniopacheco** [paypal/paypal-js#59]
### 🐞 Describe the Bug
OnApproveOrderActions.order only have the capture function 
but is missing the get function
line:
https://github.com/paypal/paypal-js/blob/main/types/components/buttons.d.ts#L32

### 🌍 Environment

- Node.js/npm: -
- OS: -
- Browser: -

**Comment by gregjopa** [comment]
Hi @antoniopacheco, thanks for reporting the issue. I added more types for the onApprove callback. This change is included in the paypal-js@2.1.7 release. Please give it a try and let me know if you noticed anything else missing.
