### ISSUE TITLE
Remove typings from DefinitelyTyped?

### ISSUE THREAD

**Issue by ReazerDev** [paypal/paypal-js#86]
Hi, I just got a Notification, that I should review the PR on the DefinitelyTyped repo and it removes the @paypal/paypal-js typings.
I just wanted to make sure, that it's correct^^ As far as I understand, paypal-js now bundles it's own typings, right?

For reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53216

**Comment by gregjopa** [comment]
@ReazerDev that is correct. This library has been upgraded to TypeScript and exports the types. We can remove it from DefinitelyTyped. Thanks for your help with this!

**Comment by ReazerDev** [comment]
Ok, I approved aswell :)
