### ISSUE TITLE
[Bug] The onClick Method is not Working Before the createOrder on Android and iOS Devices 

### ISSUE THREAD

**Issue by cfreyre** [paypal/paypal-js#99]
### 🐞 Describe the Bug

The onCLick is not Working Before the createOrder on Android and iOS Devices (before the "createOrder" method).
Works Fine in Desktop.

### 🔬 Minimal Reproduction

1.- Make a Button with onClick method
2.- In desktop works fine (before the "createOrder" method)
3.- In mobile devices the function execute after the createOrder method.

This behavior is reproducible with the Developer tools in Chrome on Desktop (simulate the mobile devices)

### 🌍 Environment

-   OS: macOs Catalinda
-   Browser: - Chrome on Desktop, Safari and Chrome on Mobile Devices

**Comment by mstuart** [comment]
Hi @cfreyre, we're looking into this. Thanks!

**Comment by gabrielo91** [comment]
Hi @cfreyre, we were trying to reproduce the error and it seems it is working fine, we used the below code snippet. We see the exact same behavior in desktop and mobile, first, the      `on click` alert is launched, and then the `creating order` one. Could you please provide some extra information about it or let us know if with such a code snippet do you have the same issue?

Thanks!

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Checkout Standard Integration</title>
    <meta charset="UTF-8" />
  </head>
  <body>
    <div id="paypal-button-container"></div>
    <script src="https://www.paypal.com/sdk/js?client-id=AWx1gpCaWDcvW0Tfxwf6gqMuvRkxVyhYPKJIEB6KVO3AdxxZJVnNaFxbQkemez5VwrqpkcMbRN8ZGJ-j"></script>
    <script>
      paypal.Buttons({
      createOrder: function (data, actions) {
          alert('creating order')
          return actions.order.create({
              purchase_units: [{
                  amount: {
                      value: '50.00'
                  }
              }]
          });
      }
  }).render('#paypal-button-container').setAttribute('onClick', alert('on click'));
    </script>
  </body>
</html>

```

**Comment by cfreyre** [comment]
Hi, thanks @gabrielo91. Working more on the error, I think it is actually not in the onClick button per se, I think it may be in the "action.resolve" function. My code calls a file in "onClick Method" and the method "actions.resolve ();" doesn't work well. I don't know if this behavior has to do with what was reported here: [https://github.com/paypal/paypal-checkout-components/issues/1657](url)

It is worth mentioning that it was working perfect a month ago.

This is my Code:

                  paypal.Buttons({
                  createOrder: function(data, actions) {
                      return actions.order.create({
                          intent:"CAPTURE",
                          shippingAddressEditable: false,
                          purchase_units: [{
                              amount: {
                                value: "500",
                                breakdown: {
                                  item_total: {
                                    currency_code: "MXN",
                                    value: "50"
                                  },
                                  shipping: {
                                    currency_code: "MXN",
                                    value: "10"
                                  }
                                }
                              },
                              invoice_id:inputVal,
                              description: "Pedido 500 realizado en example.com",
                              custom_id: inputVal,
                              shipping: {
                                method: "UPS",
                                address: {
                                  name: {
                                    full_name: "George Benson"
                                  },
                                  ...
                                  ...
                                }
                              }
                          }],
                      });
                  },
                onApprove: function(data, actions) {
                      return actions.order.capture().then(function(details) {
                          var url = "onApprove_file.php";
                          var data = details;
                          fetch(url, {
                            method: "POST",
                            body: JSON.stringify(data),
                            headers:{
                              "Content-Type": "application/json"
                            }
                          })
                          .then(response => window.location.replace("another_file.php"));
                  });
                },
                onClick: function(data, actions) {
                  return fetch("checkout_prefix.php", {
                    method: "post"
                  }).then(function(res) {
                    return res.json();
                  }).then(function(data) {
                    if (data.validationError) {
                      return actions.reject();
                    } else {
                      document.getElementById("paypal-button-container").classList.add("hidden");
                      document.getElementById("paypal-message").classList.add("hidden");
                      document.getElementById("paypal-wait").classList.remove("hidden");
                      return actions.resolve();
                    }
                  });
                }
              }).render("#paypal-button-container");
           });

**Comment by gabrielo91** [comment]
@cfreyre we were able to reproduce the bug and we are working on it now, we'll let u know when we have some news. Thanks!

**Comment by gabrielo91** [comment]
Hi @cfreyre, the fix has been released, please try it out and let us know, thanks!

**Comment by gabrielo91** [comment]
Hi @cfreyre, we released the fix. Please re-open this if it’s still an issue for you.

**Comment by cfreyre** [comment]
@gabrielo91 Thank You . It is Working Fine. ¡Muchas Gracias! ; )
